name: Build Package Manually
on: [workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm_cortex-a7
          - arm_cortex-a9
          - mips_24kc
          - mips_4kec
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: amnezia-wg-tools

      - name: Store amnezia-wg-tools Artefacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-amnezia-wg-tools
          path: bin/packages/${{ matrix.arch }}/action/*.ipk
