name: Build Package Manually
on: [workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - mips_24kc

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: amnezia-wireguard-tools
          V: s

      # - name: Store packages
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.arch}}-packages
      #     path: bin/packages/${{ matrix.arch }}/packages/*.ipk