name: Build Package Manually
on: [workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - mipsel_24kc

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: amnezia-wg-tools

      - name: Dump structure
        run: find ./ -type d

      - name: Store awgtools
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-awgtools
          path: bin/packages/${{ matrix.arch }}/awgtools/*.ipk